<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Error fix</title>
</head><body><span style="font-size: 15pt"><b><u>When I ran the ntlmrelay.py and mitm6.py commands, I couldn't capture any information about the relay got stuck on this output:</u></b><br/>
<br/>
<br/>
<br/>
<i>[*] Servers started, waiting for connections<br/>
<br/>
[*] HTTPD: Received connection from ::ffff:172.16.223.134, attacking target ldaps://172.16.223.133<br/>
<br/>
[*] HTTPD: Client requested path: /wpad.dat<br/>
<br/>
[*] HTTPD: Client requested path: /wpad.dat<br/>
<br/>
</i><i>[*] HTTPD: Serving PAC file to client ::ffff:172.16.223.134</i><br/>
<br/>
<br/>
<br/>
<br/>
<b>The solution was just a lack of depedences, installing these things and re-run the commands to get correct output:<br/>
</b><br/>
<i>apt update<br/>
<br/>
sudo apt-get install libssl-dev<br/>
<br/>
</i><i>sudo pip install service_identity</i><br/>
</span></body></html>